# -*- coding: utf-8 -*-
"""Takım8_Elçin_Taha_Merve.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PKRsqNe29aoKnSqV4-vA7A0F3bK_Ir8i
"""

import random
import time


class Otomat():

    def __init__(self, durum="Kapalı", miktar=100, fiyat=10):
        self.durum = durum
        self.miktar = miktar
        self.fiyat = fiyat

    def open(self):
        if self.durum == "Açık":
            print("Otomat zaten açık.")
        else:
            print("Otomat açılıyor...")
            self.durum = "Açık"
            time.sleep(0.5)
            print("Otomat açıldı.")

    def close(self):
        if self.durum == "Kapalı":
            print("Otomat zaten kapalı.")
        else:
            print("Otomat kapanıyor...")
            self.durum = "Kapalı"
            time.sleep(0.5)
            print("Otomat kapandı.")

    def kahve_al(self):
        if self.miktar <= 0:
            print("Otomatta kahve yok.")
        else:
            self.miktar -= 1
            print(f"Kahve fiyatı : {self.fiyat}₺")
            para = int(input("Otomata koyacağınız parayı yazınız. : "))
            while True:
                if para < int(self.fiyat):
                    para = int(input("Lütfen yeterli miktarda para girin : "))
                else:
                    print("Kahveniz hazırlanıyor...")
                    time.sleep(0.5)
                    print("Afiyet olsun!"),
                    print(f"Para üstünüz {para - self.fiyat}₺")
                    print(f"Otomattaki kahve miktarı : {self.miktar}")
                    break

    def miktar_degistirme(self, yeni_miktar):
        self.miktar = yeni_miktar
        print(f"Yeni kahve miktarınız: {self.miktar}")

    def fiyat_guncelle(self, yeni_fiyat):
        print(
            f"Kahvenin fiyatı değiştirilmiştir. Eski Fiyat = {self.fiyat}₺  Yeni Fiyat = {yeni_fiyat}₺")
        self.fiyat = yeni_fiyat

    def __len__(self):
        return len(self.miktar)

    def __str__(self):
        return (f"Otomat Durumu : {self.durum}\nKahve Sayısı : {self.miktar}\nKahve Fiyatı = {self.fiyat}₺\n")

# class Kahve():
#     def __init__(self, kahve_ismi, kahve_fiyati, kahve_adeti=0):
#         self.kahve_ismi = kahve_ismi
#         self.kahve_fiyati = kahve_fiyati
#         self.kahve_adeti = kahve_adeti

#     def fiyat_guncelle(self, yeni_fiyat):
#         print(f"{self.kahve_ismi} kahvesinin fiyatı değiştirilmiştir. Eski Fiyat = {self.kahve_fiyati}  Yeni Fiyat = {yeni_fiyat}")
#         self.kahve_fiyati = yeni_fiyat


otomat = Otomat()
print("""
    
    FİLTRE KAHVE OTOMATI
    
    1.Otomat Aç
    
    2.Otomat Kapa
    
    3.Kahve Al
    
    4.Kahve Miktarını Düzenle
    
    5.Fiyat Güncelleme
    
    6.Otomat Bilgileri
    
    Çıkmak için 'q'ya basın.
    
    """)
while True:
    işlem = input("İşlemi seçiniz: ")
    if otomat.durum == "Kapalı" and işlem != "1":
        print("Otomat kapalı, işlem yapmak için açmalısınız.")
    else:
        if işlem == "q":
            print("Program sonlandırılıyor...")
            time.sleep(0.5)
            print("Programdan çıkıldı.")
            print("\n")
            break
        elif işlem == "1":
            otomat.open()
            print("\n")
        elif işlem == "2":
            otomat.close()
            print("\n")
        elif işlem == "3":
            otomat.kahve_al()
            print("\n")
        elif işlem == "4":
            print(f"Güncel kahve miktarı: {otomat.miktar}")
            yeni_miktar = int(input("Yeni kahve miktarını giriniz : "))
            otomat.miktar_degistirme(yeni_miktar)
            print("\n")
        elif işlem == "5":
            print(f"Şuanki kahve fiyatı: {otomat.fiyat}₺")
            yeni_fiyat = int(input("Yeni kahve fiyatını giriniz : "))
            otomat.fiyat_guncelle(yeni_fiyat)
            print("\n")
        elif işlem == "6":
            print(otomat)
            print("\n")
        else:
            print("Geçersiz işlem...")
            print("\n")